name: "Lint PR"
on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout proposed PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Set ENV
        run: |
         echo "hello world"
        env:
          FAKE_SECRET_FOR_DEMO: ${{ secrets.FAKE_SECRET_FOR_DEMO }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: NPM install
        run: npm install

      - name: NPM build
        run: npm run build

      - name: Print secret
        run: |
          echo "FAKE_SECRET_FOR_DEMO = ${{ secrets.FAKE_SECRET_FOR_DEMO }}"
          

        
